### ISSUE TITLE
Class Naming from snakeCase to CamelCase

### ISSUE THREAD

**Issue by selimacerbas** [wa11breaker/flutter-bloc.nvim#2]
I have been recently using this tool, I have realised that the generated Bloc or Cubit class were written using snakeCase. As best practice, the class names should written in CamelCase. Can a change be done in there? For example in this screenshot change from themeBloc to ThemeBloc.

<img width="642" alt="Screenshot 2024-11-17 at 14 18 47" src="https://github.com/user-attachments/assets/7b5504ea-42d5-4e54-9c49-908ac2822a24">

**Comment by wa11breaker** [comment]
While inputting the bloc/cubit name, use CamelCase. The plugin will automatically create the files in snake case.
