### ISSUE TITLE
Class Wrapping

### ISSUE THREAD

**Issue by selimacerbas** [wa11breaker/flutter-bloc.nvim#3]
Do you plan to support class wrapping for Bloc and Cubit?
<img width="807" alt="Screenshot 2024-11-17 at 14 35 39" src="https://github.com/user-attachments/assets/cdd5b702-cfa8-4db8-b35c-491794947757">

**Comment by wa11breaker** [comment]
This is there in the pipeline

**Comment by wa11breaker** [comment]
Added code action support https://github.com/wa11breaker/flutter-bloc.nvim/pull/5

**Comment by selimacerbas** [comment]
Thank you very much looks great!
