### ISSUE TITLE
Support Data Class Generation Macros

### ISSUE THREAD

**Issue by selimacerbas** [wa11breaker/flutter-bloc.nvim#7]
Bloc + Equatable is very cool but creating boilerplate code for Constructor, probs from Equatable, toString method, copyWith method, or JSON serialisation can be boring. There is a VSCode plugin called Data Class Generator becomes very handy to fix this problem. Same functionality could be created for NVIM sessions using Lua. The example functionality could be seen at this link; https://github.com/huang12zheng/Dart-Data-Class-Generator

**Comment by wa11breaker** [comment]
I’m currently working on it. Feel free to keep an eye on [this repository](https://github.com/wa11breaker/dart-data-class-generator.nvim); I’ll be making progress on it over the weekend.

**Comment by selimacerbas** [comment]
Great job, I am currently following it
